version: '3'
services:
  magic:
    
    # image: southamerica-east1-docker.pkg.dev/gcp-project/folder/image:tag
    command: mage start BIX-MAGE-PIPELINES
    env_file:
      - dev.env
    build:
      context: ./docker/mageai
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/BIX-MAGE-PIPELINES
      ENV: dev
 
      GOOGLE_APPLICATION_CREDENTIALS: /home/src/mage_data/mageai-job-runner.json
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/BIX-MAGE-PIPELINES
      - ./secrets/mageai-job-runner.json:/home/src/mage_data/mageai-job-runner.json
    restart: on-failure:5