version: 0.1.1

dev:
  # PostgresSQL
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: postgres
  POSTGRES_SCHEMA: venda
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_HOST: 127.0.0.1
  POSTGRES_PORT: 5432
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: /home/src/mage_data/mageai-job-runner.json